// <auto-generated />
namespace CribbApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class neighborhoods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(neighborhoods));
        
        string IMigrationMetadata.Id
        {
            get { return "202011170158402_neighborhoods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
